### ISSUE TITLE
Determine length of the blinding factor

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#102]
How many bits the blinding factor should have? In #90 and earlier PRs we decided to store it in 64 bits. 64 bit security [is not considered reassuring today](https://crypto.stackexchange.com/questions/63536/how-reassuring-is-64-bit-insecurity) but 64 bits is just the blinding factor length and the length of the input data to the hash function is higher.

Is 64 bit blinding factor OK?

**Comment by mhluongo** [comment]
As the blinding factor is an additional layer of security, we should be good here.
