### ISSUE TITLE
Governable parameters for Bridge contract

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#147]
There is a bunch of TODOs in the `Bridge` contract about making some parameters governable. Part of them will become governable during the work on upgradeability. The remaining parameters will have to be covered separately, as a part of work on this issue.

**Comment by nkuba** [comment]
Are we expecting to implement a governance contract similar to the `WalletRegistryGovernance` and `RandomBeaconGovernance`?

**Comment by pdyraga** [comment]
Correct, we need it. It's always less error-prone to update one parameter without having to pass the current values of other parameters.

**Comment by pdyraga** [comment]
All parameters can now be updated in `Bridge`. `BridgeGovernance` will be implemented in https://github.com/keep-network/tbtc-v2/issues/249.
