### ISSUE TITLE
Deploy Bridge behind transparent upgradeable proxy

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#161]
We want to be able to upgrade `Bridge` implementation if needed.

**Comment by nkuba** [comment]
Is this a duplicate of https://github.com/keep-network/tbtc-v2/issues/141?

**Comment by pdyraga** [comment]
#141 will be a parent of #161 - still need to cleanup them. Having `Bridge` behind a transparent proxy is not a whole story.

**Comment by pdyraga** [comment]
Wrong. This issue is a duplicate of #141. The epic is #39.
