### ISSUE TITLE
Reduce size of the Bridge contract

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#165]
The `Bridge.sol` contract still grows and its size is close to the `24KB` limit. This task is about reducing its size to an acceptable level, possibly by extracting common functionalities to separate linked libraries.

**Comment by pdyraga** [comment]
I suggest we extract to separate libraries:
- reveal logic
- sweep logic
- redemption proof logic

There is much more code we will have to add to `Bridge` contract: governance, wallet lifecycle, slashing, fraud proofs.

**Comment by lukasz-zimnoch** [comment]
> 

I think reveal & sweep is strongly connected so they probably must live in the same lib to avoid the glue code. Same for redemption requests and proofs.

**Comment by pdyraga** [comment]
Sure, we can have them in the same library if that makes sense! We could make separate libraries for deposit and redemptions flow as well.
