### ISSUE TITLE
ETH refunds for Bridge maintainers

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#171]
[#2824](https://github.com/keep-network/keep-core/issues/2824) implements RFC 6 (https://github.com/keep-network/tbtc-v2/pull/115) for ECDSA and random beacon. The same has to be done for Bridge maintainers.

## Public-knowledge functions executed by maintainers

We want to have a separate contract that can easily be unplugged from `Bridge` and that will allow the DAO to specify the list of maintainers who will get reimbursement. This way we reduce the problem of frontrunning to a smaller group of nodes that should respect round-robin submissions.

Depends on #141

The functions we want to cover are:
- `submitSweepProof`
- `submitRedemptionProof`
- `submitMovingFundsProof`
- `requestNewWallet`
- `notifyCloseableWallet`
- `notifyWalletClosingPeriodElapsed`

## Operator-only functions

Should be covered similar to operator-only functions of ECDSA `WalletRegistry`.
The functions we want to cover are:
- `submitMovingFundsCommitment`
- `notifyMovingFundsBelowDust`
- `defeatFraudChallenge`

**Comment by michalinacienciala** [comment]
Recently two new functions were added:
`defeatFraudChallengeWithHeartbeat` (operator-only)
`submitMovedFundsSweepProof` (public knowledge)

**Comment by michalinacienciala** [comment]
@pdyraga, should `notifyMovingFundsBelowDust` really be operator-only? Isn't it public knowledge?
If it's operator-only, I need to update the incentives info for that function in https://github.com/keep-network/tbtc-v2/pull/272.

**Comment by michalinacienciala** [comment]
Also, @pdyraga, one more thing. What about reimbursement for `notifyWalletHeartbeatFailed`?
In https://github.com/keep-network/tbtc-v2/blob/7b3cb19f6860cfc32677b15d5de643a9ee0f0f51/docs/rfc/rfc-6.adoc#rfc-6-transaction-incentives we state that"
> No submission order will be enforced on-chain for the heartbeat failure transaction and **the transaction submitter will have ETH cost reimbursed**.

Does that refer to the `Wallets.notifyWalletHeartbeatFailed` or maybe to the `WalletRegistry .notifyOperatorInactivity`?
In https://github.com/keep-network/tbtc-v2/pull/272 I marked the `notifyWalletHeartbeatFailed` as reimbursable, but now I'm not sure if that's right...
