### ISSUE TITLE
Break `Bridge.test.ts` into smaller parts

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#173]
The `Bridge.test.ts` file became too large and should be split into smaller files.

**Comment by pdyraga** [comment]
My proposition:
- `Bridge.Vaults.test.ts` (`setVaultStatus`)
- `Bridge.Deposit.test.ts` (`revealDeposit`, `submitSweepProof`)
- `Bridge.Redemption.test.ts` (`requestRedemption`, `submitRedemptionProof`, `notifyRedemptionTimeout`)
