### ISSUE TITLE
Rename `tbtc-ts` to `typescript`

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#178]
We want to rename `tbtc-v2/tbtc-ts` to `tbtc-v2/typescript` to keep it aligned with `/solidity`. The package should be published as `@keep-network/tbtc-v2.ts` (or `tbtc.ts` starting with v2 version: still to be decided)

**Comment by lukasz-zimnoch** [comment]
Maybe we should publish it as `@keep-network/tbtc-v2.ts`? The `@keep-network/tbtc.ts` may be confusing as it looks like the TypeScript version of `tbtc.js` for v1.

**Comment by pdyraga** [comment]
> Maybe we should publish it as `@keep-network/tbtc-v2.ts`? The `@keep-network/tbtc.ts` may be confusing as it looks like the TypeScript version of `tbtc.js` for v1.

Yes, good point! I'll edit the issue description.

**Comment by nkuba** [comment]
I prefer not including `v2` in the package name and start versioning with `2.0.0`. We did similar for [@keep-network/random-beacon](https://github.com/keep-network/keep-core/blob/4d99ad4089c259d259ef8cb2bd061dbc1d6aa796/solidity/random-beacon/package.json#L2-L3) and [@keep-network/ecdsa](https://github.com/keep-network/keep-core/blob/4d99ad4089c259d259ef8cb2bd061dbc1d6aa796/solidity/ecdsa/package.json#L2-L3).

We should also align [`@keep-network/tbtc`](https://github.com/keep-network/tbtc-v2/blob/31003503c9e83d24a2ec34e71f158e9948fe1e9a/solidity/package.json#L2-L3) with this convention.

**Comment by lukasz-zimnoch** [comment]
> I prefer not including v2 in the package name and start versioning with 2.0.0. We did similar for [@keep-network/random-beacon](https://github.com/keep-network/keep-core/blob/4d99ad4089c259d259ef8cb2bd061dbc1d6aa796/solidity/random-beacon/package.json#L2-L3) and [@keep-network/ecdsa](https://github.com/keep-network/keep-core/blob/4d99ad4089c259d259ef8cb2bd061dbc1d6aa796/solidity/ecdsa/package.json#L2-L3).
We should also align [@keep-network/tbtc](https://github.com/keep-network/tbtc-v2/blob/31003503c9e83d24a2ec34e71f158e9948fe1e9a/solidity/package.json#L2-L3) with this convention.

Is that reasoning correct? According to semver rules, bumping up the major version means API-incompatible changes. However, in our case, tBTC v2 means a new separate system, not the existing system with breaking changes. I'm afraid that this will bring confusion as people can think the `tbtc.ts@2.0.0` still refers to the well-known v1 system where some API changes have been made.
