### ISSUE TITLE
Potential improvements to wallet lifecycle

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#180]
This issue is a followup of #176 review/discussion. 

1. Say that `wallet_min_btc` (`minBtcBalance` in Solidity code) is set to 10 BTC. It means that if the current active wallet is old enough and it has at least 10 BTC we allow for wallet creation to kick off. But later, if the same wallet has just 1 satoshi less (10 BTC - 1 sat), we consider it closeable. Shouldn't we have some additional margin?

2. We attempt to move funds if the wallet balance is below `wallet_min_btc`. What if it is 1 sat? Can we guarantee sending 1 sat is doable on Bitcoin? This feels like a potential attack vector when someone redeems such an amount from the given wallet so that the amount left is not transferable and the wallet gets slashed for not moving funds to another wallet in time. Shouldn't we have some additional dust threshold so that closing the wallet is possible without moving funds?

**Comment by beaushinkle** [comment]
After hashing this out internally, here's the tentative solution:

We disambiguate `wallet_min_btc` into three separate governable params: 
+ The minimum amount of btc the active wallet needs to have before we make a new active wallet (`wallet_min_creation_btc`)
+ The minimum amount of btc a non-active wallet needs to have before we motion to close+transfer (`wallet_min_closure_btc`)
+ The amount of btc at which if a non-active wallet has less than, we motion to close and *don't* transfer (`wallet_dust_leftover`).

So if `wallet_dust_leftover = 1000 sats` and `wallet_min_closure_btc = 1 btc`, and the current balance of a wallet is 5 btc then when:

+ That wallet gets a 4.5 btc redemption (leaving it at 0.5 btc), we close+transfer that 0.5 btc to another wallet
+ That wallet gets a (5-500 sat) redemption (leaving it 500 sats), we close that wallet, abandoning those 500 sats. We can maintain the peg via a governance donation.

**Comment by beaushinkle** [comment]
@pdyraga good to close this?
