### ISSUE TITLE
Calling the random beacon

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#36]
In tBTC v1, random beacon provided a new relay entry asynchronously, after sortition pool selected group members, and after new bonded ECDSA keep was created. Random beacon was getting called for each new deposit and in case it did not provide an entry, new deposits could get created anyway.

We need to define when and how the random beacon is called for tBTC v2.

Questions we need to answer (and there is more for sure):
- When is the random beacon called?
- Can a new entry be provided after the group selection?
- What happens if the beacon is busy?

**Comment by eth-r** [comment]
If we leave group selection up to the market to do based on the reward:gas ratio, I think the best way to do it would be something approximately as follows:

- anybody can call the "start new group selection" function on tBTC, which:
  1. requires that a governance-defined minimum payment is provided
  2. calls the random beacon for a new entry passing the payment onward along with gas limit etc.
  3. if the beacon is not busy, records who called this function for future use and blocks the "start new group selection" function from being called
- now the random beacon produces an entry, and once it is done it calls tBTC with the new entry:
  1. tBTC performs the actual sortition
  2. a new wallet is formed
  3. the original caller is reimbursed if everything is successful and "start new group selection" becomes available again

This is able to handle busy beacon, unsuccessful sortition, etc. and retry gracefully without being too vulnerable to griefing by e.g. providing insufficient gas money to the beacon. Using the random beacon entry immediately is also better for preventing sortition pool manipulation and other shenanigans.
