### ISSUE TITLE
Determine minting and redemption fee structure

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#431]
CoinList charges a flat 0.25% trading fee to wrap or unwrap WBTC (https://coinlist.co/help/what-are-the-fees-to-wrap-and-unwrap-wbtc). If we want to maintain the same fee, for the January release, we have two options:

- If the treasury should receive the fee at the moment of sweeping, set the Deposit fee to 0.25% and the Optimistic Minting fee to 0%.
- If the treasury should receive the fee at the moment of finalizing the Optimistic Mint, set the Optimistic Mint fee to 0.25% and the Deposit Fee to 0%.

To be done here:
- [x] @mhluongo and @pdyraga to determine the fee structure
- [x] @lukasz-zimnoch and @tomaszslabon to prepare an extra mainnet deployment script step to update fees

**Comment by mhluongo** [comment]
My default: Let's start with an optimistic minting fee of 0.2% (rather than 0.25%) and a 0% deposit fee.

If this means we'll be slightly undercollateralized on the BTC side after a sweep due to Bitcoin network fees, we can burn the excess tBTC to make up the difference when sweeping launches.
