### ISSUE TITLE
Determine and adjust deposit lock time

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#432]
We need to determine and update the deposit lock time. 6mo feels like a good value but we could consider increasing it to 9mo/12mo in case of any unexpected issues after the deployment.

Steps that need to be taken:
- [x] Determine the lock time (product question) - @mhluongo @pdyraga 
- [x] Update the lock time in smart contracts - @lukasz-zimnoch @tomaszslabon (#452)
- [x] Update the lock time in the typescript library - @michalsmiarowski @lukasz-zimnoch (#452)
- [x] Reflect the change in the dashboard if needed (update copy) - @michalsmiarowski

**Comment by mhluongo** [comment]
Let's launch with a 9 month lock time in case the backlog of sweeps is larger than we're anticipating.

**Comment by lukasz-zimnoch** [comment]
@r-czajkowski @michalsmiarowski heads-up regarding changes on the dApp front. In #452, we modified the `calculateDepositRefundLocktime` function by adding an optional `depositRefundLocktimeDuration`. Please keep in mind that you need to provide a proper `depositRefundLocktimeDuration` value while computing the `refundLocktime` hex for `calculateDepositAddress`. The proper value in the context of contract changes presented in #452 is `21772800`. This is 9 months in seconds, assuming 1 month = 4 weeks = 28 days. Then, you must reveal a deposit within 14 days, counting from the timestamp you use as deposit creation.
