### ISSUE TITLE
Determine deposit dust threshold

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#436]
We need to determine the deposit dust threshold for the optimistic minting launch and reflect it in the deployment scripts. Currently, the dust threshold is set to 0.01 BTC.

To be done here:
- [x] @mhluongo and @pdyraga to determine the dust threshold
- [x] @lukasz-zimnoch and @tomaszslabon to prepare an extra mainnet deployment script step to update the threshold

**Comment by mhluongo** [comment]
I'd prefer an order of magnitude lower at maturity, but I think 0.01 is fine for now. We'll need to make sure optimistic minting maintainers and the dApp handle that appropriately as well.

**Comment by lukasz-zimnoch** [comment]
Nothing more to do here. 0.01 BTC is the default `depositDustThreshold` as set [here[(https://github.com/keep-network/tbtc-v2/blob/07f8bf577319cb7e4933ef2ae890b761ee229af6/solidity/contracts/bridge/Bridge.sol#L299)
