### ISSUE TITLE
Allow only the depositor to reveal a deposit

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#439]
Consider this scenario:
- Alice reveals her Bitcoin deposit and routes it to vault 0xABC
- Eve notices Alice's TX in the mempool and frontruns it with the same data but the vault 0xDEF

As a result, Alice's deposit lands in vault 0xDEF and not in vault 0xABC. Both 0xDEF and 0xABC have to be trusted vaults but it is still an issue given it is not what Alice was asking for.

https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/bridge/Deposit.sol#L152

**Comment by mhluongo** [comment]
A little surprised this wasn't caught in audit

**Comment by pdyraga** [comment]
Reopening as this has also be addressed in `tbtc-v2.ts` library, see [this](https://github.com/keep-network/tbtc-v2/pull/442#pullrequestreview-1232438145) comment.
