### ISSUE TITLE
TS: yarn install freezes the system | typescript

### ISSUE THREAD

**Issue by Revantark** [keep-network/tbtc-v2#509]
Trying to integrate tbtc-v2.ts in my project, but when i do 
`yarn install`
after a while, the system freezes.

It is happening in the postInstall script `npm rebuild`

To reproduce :

1. clone tbtc-v2 repo;
2. cd typescript
3. run `yarn install`

this just hangs forever

**Comment by pdyraga** [comment]
What is the Node and Yarn version you are using? Please check [the build prerequisites](https://github.com/keep-network/tbtc-v2/tree/main/solidity#prerequisites) section in the docs.

**Comment by Revantark** [comment]
> What is the Node and Yarn version you are using? Please check [the build prerequisites](https://github.com/keep-network/tbtc-v2/tree/main/solidity#prerequisites) section in the docs.

Node : v18.12.1
yarn: v1.22.19

**Comment by lukasz-zimnoch** [comment]
@Revantark, thanks for reporting! The problem you observed sometimes happens when using Node versions greater than 14. We need to investigate it and develop a solution. As a short-term workaround, I recommend you use Node 14. Sorry for the inconvenience!

**Comment by Revantark** [comment]
> 

`node-gyp` rebuild fails on `bcrypto` package.

Using node 14

**Comment by Revantark** [comment]
> @Revantark, please make sure you have all OS-specific prerequisites of `node-gyp` listed here: https://github.com/nodejs/node-gyp#installation

@lukasz-zimnoch 
I build the package successfully thanks.

But when using it in a project, I'm getting this error
`Cannot find module 'bcrypto.node'` from tbtc-v2.ts

I'm using yarn to link the local package to a project.

**Comment by Revantark** [comment]
@lukasz-zimnoch Yes, I was doing it. But still i get `Cannot find module 'bcrypto.node'` error in a node project.

How to reproduce :

yarn: 1.22.19
node: v14

1. create an empty node project using `npm init`
2. run `npm install @keep-network/tbtc-v2.ts`
3. run `npm rebuild`
4. run  `npm start`

Error: Cannot find module 'bcrypto.node'

**Comment by pdyraga** [comment]
@lukasz-zimnoch In which places do we need `bcrypto` in `tbtc-v2.ts`? In the worst case, we can copy only the code needed.

**Comment by lukasz-zimnoch** [comment]
> @lukasz-zimnoch In which places do we need `bcrypto` in `tbtc-v2.ts`? In the worst case, we can copy only the code needed.

All hash computations. Copying is not an option as this is native code that must be compiled for specific targets.

**Comment by lukasz-zimnoch** [comment]
We are working on removing the problematic `bcrypto` and `bcoin` dependencies. Once done, the problem described here will be solved as well. Closing this issue in favor of https://github.com/keep-network/tbtc-v2/issues/695
