### ISSUE TITLE
Documentation: How are wallets generated

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#528]
To be done:
- [x] Explain how it works today and how it is going to work on docs.threshold.network
- [x] Publish a narrative blog post

**Comment by beaushinkle** [comment]
the docs are up: https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/fundamentals/tbtc-v2/wallet-generation

the blog post is handed off to growth for sprucing up
