### ISSUE TITLE
Fix System tests

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#531]
For the last 5 days System Tests keep failing. All failure reasons are mostly about the infrastructure or timing issues.

We need to stabilize them.

2023-02-13
https://github.com/keep-network/tbtc-v2/actions/runs/4158928738/jobs/7194500178
Failed in `system-tests-deposit-redemption` in "Install Solidity dependencies" step with:
> mv: cannot stat '/home/runner/work/tbtc-v2/tbtc-v2/solidity/external/npm/@keep-network/keep-core/artifacts/TokenStaking.json': No such file or directory

2023-02-12
https://github.com/keep-network/tbtc-v2/actions/runs/4153790155/jobs/7185650740
Failed in `system-tests-deposit-redemption` in "Install Solidity dependencies" step with:
> cp: cannot create regular file '/home/runner/work/tbtc-v2/tbtc-v2/solidity/external/npm/@keep-network/keep-core/artifacts/TestModUtils.json': File exists

2023-02-11
https://github.com/keep-network/tbtc-v2/actions/runs/4148695125/jobs/7176940147
Failed in `system-tests-deposit-redemption` in "Install Solidity dependencies" step with:
> cp: cannot create regular file '/home/runner/work/tbtc-v2/tbtc-v2/solidity/external/npm/@keep-network/keep-core/artifacts/BeaconBackportRewards.json': File exists

2023-02-10
https://github.com/keep-network/tbtc-v2/actions/runs/4139583744/jobs/7157317324
Failed in `system-tests-deposit-redemption`
>  1) System Test - Deposit and redemption
>      when deposit is made and revealed
>         when deposit is swept and sweep proof submitted
>           "before all" hook: sweep the deposit and submit sweep proof for "should broadcast the sweep transaction on the Bitcoin network":
>     Error: Electrum action failure: [tx 535f5d2b8acba1b478be80a6ebece6d90542360f5dcd7839a32c3f39935e9c36 not in block at height 2,419,483]

2023-02-08
https://github.com/keep-network/tbtc-v2/actions/runs/4119445814/jobs/7113116145
Failed in `system-tests-minting-unminting` in "Install Solidity dependencies" step with:
> cp: cannot create directory '/home/runner/work/tbtc-v2/tbtc-v2/solidity/external/npm/@keep-network/keep-core/artifacts': File exists

**Comment by michalinacienciala** [comment]
2023-03-07
https://github.com/keep-network/tbtc-v2/actions/runs/4349250793/jobs/7598698598
Failed in `system-tests-minting-unminting` in "Run scenario" step with:
> Error: Electrum action failure: [daemon error: DaemonError({'message': 'Transaction not found.', 'code': -1})]

This will hopefully be fixed by [https://github.com/keep-network/tbtc-v2/pull/541](https://github.com/keep-network/tbtc-v2/pull/541?)
