### ISSUE TITLE
tBTC Documentation: Minting Walkthrough

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/tbtc-v2#599]
Need a quick start guide for minting tBTC, with screenshots from the UI and explanation.

Include the full flow, from:
- [x] What you need before you start
- [x] How to set up Green Wallet network
- [x] Connecting your wallet
- [x] Step 1 recovery btc address & JSON
- [x] Send BTC funds
- [x] Mint tBTC & Success screen

**Comment by liz-shinn** [comment]
Live in the GitBook as a Preview here: https://docs.threshold.network/~/changes/suMswpnkMCvZVjjynsoM/applications/tbtc-v2/tbtc-minting-walkthrough

**Comment by liz-shinn** [comment]
Request for review here: https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/~/changes/183/applications/tbtc-v2/tbtc-minting-walkthrough

**Comment by mhluongo** [comment]
Closing as this landed in [production](https://docs.threshold.network/applications/tbtc-v2/tbtc-minting-walkthrough)!
