### ISSUE TITLE
Post deployment cross-chain actions 

### ISSUE THREAD

**Issue by dimpar** [keep-network/tbtc-v2#600]
We deployed contracts supporting tBTC on 3 different cross-chains: Arbitrum, Optimims, and Polygon.
Deployment scenarios:
Arbitrum: https://github.com/keep-network/tbtc-v2/issues/577
Optimism: https://github.com/keep-network/tbtc-v2/issues/593
Polygon: https://github.com/keep-network/tbtc-v2/issues/594

Ownership of the contracts was transferred to the Council at the end of each deployment. Now, the Council needs to execute some updates on Arbitrum and Optimism. (Contracts on Polygon were deployed at the end and the Arbitrum/Optimism contract addresses were known. This is why the mapping of Arbitrum and Optimism was already done).

Arbitrum:
- [x] Map [Optimism](https://github.com/keep-network/tbtc-v2/blob/main/cross-chain/arbitrum/deploy_l2/13_update_with_optimism_in_wormhole_gateway_mapping.ts) and [Polygon](https://github.com/keep-network/tbtc-v2/blob/main/cross-chain/arbitrum/deploy_l2/14_update_with_polygon_in_wormhole_gateway_mapping.ts) gateways by executing `updateGatewayAddress()` with the right parameters. See Arbitrum Tx JSON at the bottom.
- [x] Lower the confirmation threshold. 6-of-9? (to be confirmed by the Council)
- [x] Make sure signer addresses are the same across all the supported L1, L2, and sidechain(s).

Optimism:
- [x] Transfer ownership from the "old" council address `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f` to a new one `0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA`. 
 Done in tx: [0xc044a0f4bd23cdf3070edb5a17c69c9c67bd81f0633a39963aa48196194dc63a](https://optimistic.etherscan.io/tx/0xc044a0f4bd23cdf3070edb5a17c69c9c67bd81f0633a39963aa48196194dc63a)
- [x] Map [Polygon](https://github.com/keep-network/tbtc-v2/blob/main/cross-chain/optimism/deploy_l2/14_update_with_polygon_in_wormhole_gateway_mapping.ts) gateways by executing `updateGatewayAddress()`. 
 Done in tx: [0xc044a0f4bd23cdf3070edb5a17c69c9c67bd81f0633a39963aa48196194dc63a](https://optimistic.etherscan.io/tx/0xc044a0f4bd23cdf3070edb5a17c69c9c67bd81f0633a39963aa48196194dc63a)
- [x] Make sure the confirmation threshold is the same as other L2/sidechains. 6-of-9? (to be confirmed by the Council)
- [x] Make sure signer addresses are the same across all the supported L1, L2, and sidechain(s).

Polygon:
- [x] Lower the confirmation threshold. 6-of-9? (to be confirmed by the Council)
- [x] Make sure signer addresses are the same across all the supported L1, L2, and sidechain(s).

Ethereum:
- [x] Make sure the confirmation threshold is the same as other L2/sidechains. 6-of-9? (to be confirmed by the Council)
- [x] Make sure signer addresses are the same across all the supported L1, L2, and sidechain(s).

### How-to:
- Navigate to Safe and click "Use transaction builder"
- Select Arbitrum or Optimism depending what network a transaction will be run on.
![howto](https://user-images.githubusercontent.com/3156420/233086851-ac34296f-98f7-4b89-af57-2484267f2a01.png)
- Drag and drop provided transaction JSON

<details>
  <summary>Arbitrum transaction JSON executing 'updateGatewayAddress()' with Optimism chain ID: 24, and Polygon ID: 5</summary>

```json

  
  {
    "version": "1.0",
    "chainId": "42161",
    "createdAt": 1681906161282,
    "meta":
    {
        "name": "Transactions Batch",
        "description": "",
        "txBuilderVersion": "1.13.3",
        "createdFromSafeAddress": "0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f",
        "createdFromOwnerAddress": "",
        "checksum": "0x2011fddfdac5a10975c8fdce4978414210df1b99f8a443ca71269cc549c4649e"
    },
    "transactions":
    [
        {
            "to": "0x1293a54e160D1cd7075487898d65266081A15458",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "uint16",
                        "name": "chainId",
                        "type": "uint16"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "gateway",
                        "type": "bytes32"
                    }
                ],
                "name": "updateGatewayAddress",
                "payable": false
            },
            "contractInputsValues":
            {
                "chainId": "24",
                "gateway": "0x0000000000000000000000001293a54e160D1cd7075487898d65266081A15458"
            }
        },
        {
            "to": "0x1293a54e160D1cd7075487898d65266081A15458",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "uint16",
                        "name": "chainId",
                        "type": "uint16"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "gateway",
                        "type": "bytes32"
                    }
                ],
                "name": "updateGatewayAddress",
                "payable": false
            },
            "contractInputsValues":
            {
                "chainId": "5",
                "gateway": "0x00000000000000000000000009959798B95d00a3183d20FaC298E4594E599eab"
            }
        }
    ]
}


```
</details>

<details>
  <summary>Optimism transaction JSON executing x3 'transferOwnership()' for: `L2TBTC`, `L2WormholeGateway`, and `Proxy Admin`. New owner: `0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA` </summary>

```json

{
    "version": "1.0",
    "chainId": "10",
    "createdAt": 1682068843135,
    "meta":
    {
        "name": "Transactions Batch",
        "description": "",
        "txBuilderVersion": "1.13.3",
        "createdFromSafeAddress": "0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f",
        "createdFromOwnerAddress": "",
        "checksum": "0xcefdafea1e3fcb38d67f781e3e2342b0c744c972495ec821391994027c378529"
    },
    "transactions":
    [
        {
            "to": "0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "address",
                        "name": "newOwner",
                        "type": "address"
                    }
                ],
                "name": "transferOwnership",
                "payable": false
            },
            "contractInputsValues":
            {
                "newOwner": "0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA"
            }
        },
        {
            "to": "0x1293a54e160D1cd7075487898d65266081A15458",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "address",
                        "name": "newOwner",
                        "type": "address"
                    }
                ],
                "name": "transferOwnership",
                "payable": false
            },
            "contractInputsValues":
            {
                "newOwner": "0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA"
            }
        },
        {
            "to": "0x02612d20CC087670a959Bb12cA3c5fd56C8A3DB3",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "address",
                        "name": "newOwner",
                        "type": "address"
                    }
                ],
                "name": "transferOwnership",
                "payable": false
            },
            "contractInputsValues":
            {
                "newOwner": "0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA"
            }
        }
    ]
}
```
</details>

<details>
  <summary>Optimism transaction JSON executing 'updateGatewayAddress()' with Polygon chain ID: 5 by the new owner 0x7fB..</summary>

```json

{
    "version": "1.0",
    "chainId": "10",
    "createdAt": 1681916320238,
    "meta":
    {
        "name": "Transactions Batch",
        "description": "",
        "txBuilderVersion": "1.13.3",
        "createdFromSafeAddress": "0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA",
        "createdFromOwnerAddress": "",
        "checksum": "0xb585ae048d5d8ac7bc84c9a7b618fdc4d610af26d9ada57b2a15d1e6e4a9a617"
    },
    "transactions":
    [
        {
            "to": "0x1293a54e160D1cd7075487898d65266081A15458",
            "value": "0",
            "data": null,
            "contractMethod":
            {
                "inputs":
                [
                    {
                        "internalType": "uint16",
                        "name": "chainId",
                        "type": "uint16"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "gateway",
                        "type": "bytes32"
                    }
                ],
                "name": "updateGatewayAddress",
                "payable": false
            },
            "contractInputsValues":
            {
                "chainId": "5",
                "gateway": "0x00000000000000000000000009959798B95d00a3183d20FaC298E4594E599eab"
            }
        }
    ]
}

```
</details>

**Comment by pdyraga** [comment]
There is one more thing related to https://github.com/keep-network/tbtc-v2/issues/549: the council contracts deployed are 9/9 safes except the Optimism safe at `0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA`. Let's make sure the threshold is properly lowered for them.

Also, let's make sure the signer addresses are all the same. For instance, signer `0x13F026559e3Cb36008178e7e358401d6Ed4d6743` from [Arbitrum safe](https://app.safe.global/settings/setup?safe=arb1:0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f) is not present in [Ethereum L1 council multisig](https://app.safe.global/settings/setup?safe=eth:0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f)
