### ISSUE TITLE
Deploy Threshold Council multisig on Solana

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#655]
https://squads.so  looks like a good option but we may explore other options as well. We need all Threshold Council members to have Solana wallets set up with confirmed addresses and have the multisig deployed on Solana with the same threshold as on Ethereum mainnet and L2s.

**Comment by lakejynch** [comment]
Squads multisig is deployed:
https://v3.squads.so/dashboard/M1NVajFvdzNFUHI0VUNpOUJuMmpxNmhjMjdQRVRHWDVkTjZrY3puc1ZUWkQ=
