### ISSUE TITLE
Deploy canonical tBTC token and gateway to Solana

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#659]
To be done during the work on this issue:
- [x] Create an official dev team deployer account and securely store the credentials. 
- [x] Prepare deployment scripts for Solana devnet and mainnet. Deployment scripts should include the deployment of the token, gateway, setting all L2 gateway addresses, and transferring authority to Threshold Council.
- [x] Prepare and execute the devnet deployment scenario. Add a comment to this issue or open a new one. Keep in mind to step to add Solana gateway mapping on all L2s.
- [x] Prepare and execute the mainnet deployment scenario. Add a comment to this issue or open a new one. Include the step for Threshold Council to add Solana gateway mapping on all L2s. Create a new tag, milestone, and publish a new release.

**Comment by dimpar** [comment]
Everything described in this issue except the deployment scenarios was done.
