### ISSUE TITLE
Deposit reveal and sweep proof

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#79]
Expected flow:
1. Depositor is assembling P2SH transaction using their ETH address, blinding factor, and signing group public key.
2. Depositor is revealing their deposit on Ethereum providing ETH address, blinding factor, and *something* about UTXO.
3. Wallet is executing a BTC transaction sweeping some revealed deposits. Wallet is free to chose which ones.
4. Wallet is informing Ethereum about the sweep providing SPV proof of the transaction and updates balances in the bank.

Requirements:
- TS code needs to be implemented in such a way that it is easy to extract it later to tbtc.ts library.
- We are not integrating any quickminter logic into this code but we need to keep in mind to implement the code in such a way that adding quickminter later is possible.

Open questions:
- What are we doing with UTXOs that can not be unblocked? Should the wallet be able to remove them from Ethereum and reduce unswept balances? Why would it pay for it? Or should we ignore them and filter them out in the client?
- How fees should work? Is the first UTXO, the last UTXO charged? Or are they all charged evenly on BTC side? How should we validate max fee set by depositors? It feels that we should use the same fee amount for everyone in the batch and just ensure that it is not higher than the individual max fees set. Is it possible to validate individual max fees at all?
- What is happening if one of the transactions in the swept batch does not meet some requirements, for example the max fee? Do we allow to confirm other UTXOs and leaving this one? Sweep transaction already happened.

TODO:
- [x] TS code for assembling P2SH transaction (https://github.com/keep-network/tbtc-v2/pull/81)
- [ ] TS code for revealing P2SH transaction
- [x] Solidity code for revealing deposits (protect against overwriting by malicious actors) (https://github.com/keep-network/tbtc-v2/pull/82 and https://github.com/keep-network/tbtc-v2/pull/90)
- [x] TS code for assembling BTC sweep transaction (no logic for filtering out transactions for sweeping) (https://github.com/keep-network/tbtc-v2/pull/96)
- [ ] TS code for assembling SPV proof (https://github.com/keep-network/tbtc-v2/pull/86)
- [x] Solidity code for validating SPV proof (https://github.com/keep-network/tbtc-v2/pull/92 or https://github.com/keep-network/tbtc-v2/pull/106)
- [x] Draft code for updating Bank swept balances (https://github.com/keep-network/tbtc-v2/pull/92 or https://github.com/keep-network/tbtc-v2/pull/106)
- [x] CI config for TypeScript library (https://github.com/keep-network/tbtc-v2/pull/101)

**Comment by pdyraga** [comment]
The current implementation, as proposed in #82, works only for P2SH transactions given that it is expected that `txInputVector` used for SPV proofs contains depositor Ethereum address.

For P2SH, deposit output is locked using the following `scriptPubKey`: `OP_HASH160 <redeemScript hash> OP_EQUAL`. When the wallet sweeps, it constructs a P2PKH transaction using the P2SH outputs as inputs. To unlock each input it must provide `scriptSig` as follows: `<signature> <public key> <redeemScript>`. The `<redeemScript>` contains the Ethereum depositor address so it can be read [from the input vector](https://github.com/keep-network/tbtc-v2/blob/3dbbaae81226e88047ee2f5b8febe1e6d30d28f5/solidity/contracts/bridge/Bridge.sol#L128) provided as sweep proof function calldata.

For Segwit P2WSH transactions, depositor address is not included in `txInputVector` so the proposed scheme is not going to work for Segwit transactions.

If a deposit transaction is made as Segwit P2WSH, its output is locked using `scriptPubKey`: `<OP_0> <redeemScript hash>`. When the wallet sweeps, it constructs a P2WPKH transaction using P2WSH outputs as inputs. But, in that case, the `scriptSig` fields must be empty and the data that normally land here must be in the witness field which is not included in transaction data. Because of that, we can no longer read Ethereum depositor address upon sweep as the redeem script is not present.

There are four options we see to address this problem, listed below.

### Option 1: Only P2SH supported + cheap deposit reveal

We will stay with the current implementation and do not support Bitcoin Segwit transactions in the Bridge.

The advantage of this solution is cheap reveal transaction - about 50k of gas in the current implementation. The dApp controls the generated address so if we generate only P2SH addresses, no Segwit deposits should be directed towards the bridge.

The disadvantage is not supporting P2WSH being an improvement to Bitcoin, especially given its high [adoption rate](https://en.bitcoin.it/wiki/Bech32_adoption). One more potential risk is how expensive is reading `fundingTxHash`, `fundingOutputIndex` and P2SH script depositor address from `txInputVector` in the sweep transactions. If this is expensive, the current solution where we need to resolve these values in a sweep TX from `txInputVector` and map them to the revealed deposit might not be acceptable.

### Option 2: More expensive deposit reveal, P2SH and P2WSH supported

We can modify `revealDeposit` function signature from:

```
    function revealDeposit(
        bytes32 fundingTxHash,
        uint8 fundingOutputIndex,
        uint64 blindingFactor,
        bytes calldata refundPubKey,
        uint64 amount,
        address vault
    ) external
```

to:
```
    function revealDeposit(
        bytes4 txVersion,
        bytes memory txInputVector,
        bytes memory txOutputVector,
        bytes4 txLocktime,
        address depositorAddress,
        uint64 blindingFactor,
        bytes calldata refundPubKey,
        address vault
)
```

In the `revalDeposit` function, we will calculate `bytes32 fundingTxHash` and `uint8 fundingOutputIndex` from the provided parameters, we will extract deposit amount and map them to the depositor address: `keccak256(fundingTxHash | fundingOutputIndex) -> <depositorAddress, amount>`. All parameters to `revealDeposit` will be provided by dApp and read from Electrum server that observes transactions directed towards the given P2SH or P2WSH address. 

Sweep function becomes easier: we can read unswept balances using `fundingTxHash | fundingOutputIndex` key and `amount` is not something user-declared but is calculated from the provided data. If the given `fundingTxHash` can be proven using SPV proof, we are fine.

The risk of this option is how expensive calculating `bytes32 fundingTxHash` and `uint8 fundingOutputIndex` is. It means the depositor needs to pay more than 53k of gas for their reveal transaction.

### Option 3: Reveal is split into two phases, P2SH and P2WSH supported

In this option, the depositor will commit to their `bytes32 fundingTxHash` and `uint8 fundingOutputIndex` by publishing a hash. The commitment needs to happen on Ethereum so that we do not have to implement any consensus mechanism. Once the commitment receives enough confirmations, the depositor can reveal P2SH info in plaintext off-chain and have their deposit swept. 

The cost of this option is a less friendly deposit experience: the depositor needs to commit, have Etherum transaction mined and sufficiently confirmed before revealing. Also, there is a class of attacks possible by a malicious wallet on a forked Ethereum chain - something that does not exist in options 2 and 3. The off-chain reveal adds some implementation and deployment complexity: dApp no longer communicates only with Ehtereum and Bitcoin but it also needs to talk to Threshold Network nodes.

### Option 4: the wallet decides who receives balance updates

Threshold members of ECDSA wallet can sign information on who is receiving balance updates in the sweep function. SPV proof is still validated so a malicious wallet can not print arbitrary amounts of money but it can steal other people's balances in the Bank, along with BTC they deposited. The risk is two times higher than in other options earlier presented.

**Comment by lukasz-zimnoch** [comment]
Regarding the implementation, we have triggered implementations of options 1 and 2 (described in https://github.com/keep-network/tbtc-v2/issues/79#issuecomment-1004909533) simultaneously as they were the most promising ones. We were interested in checking the pros and cons of both approaches and their gas costs. Results are as follows:

Option 1 (https://github.com/keep-network/tbtc-v2/pull/92):
- does not support witness
- requires deposit transaction SPV proof for individual deposit sweep proof in case the batch sweep proof can not go through for some reason
- amounts declared by depositors and there is no trusted way to verify their correctness during sweep
- reveal costs ~50-60k
- sweep costs ~245k for a single input, ~540k for 5 inputs

Option 2 (https://github.com/keep-network/tbtc-v2/pull/106):
- supports witness
- allows to a single transaction sweep proof, without requiring additional deposit transaction sweep proof in case the batch sweep proof can not go through for some reason
- amounts inferred from deposit transaction during reveal and proven implicitly at sweep stage
- reveal costs ~100k but we can try to optimize it to ~75k-80k
- sweep costs ~196k for a single input, ~355k for 5 inputs

We deemed option 2 to be far more secure and is more attractive gas-wise during the sweep, despite being a bit more expensive on the reveal stage. Having that said, we canceled the work on option 1 and focused on option 2.
